name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Captive Portal
            directory: captive-portal
          - name: Webserver v2
            directory: v2
          - name: Webserver v3
            directory: v3
    steps:
      - name: Clone the repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
      - name: Set up Node.JS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
      - name: Install dependencies
        run: npm install
      - name: Build ${{ matrix.name }}
        run: npm run build
        working-directory: packages/${{ matrix.directory }}
